### ISSUE TITLE
States missing after adding device

### ISSUE THREAD

**Issue by t-mon** [guh/guh-webinterface#37]
The states (and sometimes the controls) of a device are missing after adding a device:
- 1. adding device
- 2. open device details of added device
- 3. states missing
- 4 refresh page
- 5 states appear

**Browser**
Mozilla Firefox 41.0

**Comment by t-mon** [comment]
The states are here now, but they will not be updated until I refresh the page. (the API events will be ignored). Even if I execute the update action the states are not updated!

**Comment by rhythm-section** [comment]
Should now work. Please reopen if this bug occurs again.
