### ISSUE TITLE
Double and Float values should be rounded

### ISSUE THREAD

**Issue by t-mon** [guh/guh-webinterface#90]
A double value should not have more than 2 decimal places. If there are more than 2 decimal places, the value should be rounded, not cut off.

![partlist2](https://cloud.githubusercontent.com/assets/6507449/12142831/6b43fb66-b47b-11e5-9bb6-baadac4827eb.png)

**Comment by rhythm-section** [comment]
See https://github.com/guh/guh-webinterface/pull/91
